application:
  hooks:
      post-app-deploy: ./hooks/post-app-deploy.js
  runtimeManifest:
    packages:
      product-commerce:
        license: MIT
        actions:
          $include: ./actions/product/commerce/actions.config.yaml
      customer-commerce:
        license: MIT
        actions:
          $include: ./actions/customer/commerce/actions.config.yaml
      order-commerce:
        license: MIT
        actions:
          $include: ./actions/order/commerce/actions.config.yaml
      subscriber-commerce:
        license: MIT
        actions:
          $include: ./actions/subscriber/commerce/actions.config.yaml
productDependencies:
  - code: COMMC
    minVersion: 2.4.4
    maxVersion: 2.4.8
