application:
  runtimeManifest:
    packages:
      product-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/product/commerce/actions.config.yaml
      customer-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/customer/commerce/actions.config.yaml
      order-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/order/commerce/actions.config.yaml
      subscriber-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/subscriber/commerce/actions.config.yaml
productDependencies:
  - code: COMMC
    minVersion: 2.4.4
