consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    $include: ../../auth.config.yaml
    DOTDIGITAL_LIST_CUSTOMER: $DOTDIGITAL_LIST_CUSTOMER
    DOTDIGITAL_DATAFIELD_MAPPING: $DOTDIGITAL_DATAFIELD_MAPPING
  annotations:
    require-adobe-auth: true
    final: true
