consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    $include: ../../auth.config.yaml
    DOTDIGITAL_LIST_SUBSCRIBER: $DOTDIGITAL_LIST_SUBSCRIBER
  annotations:
    require-adobe-auth: true
    final: true
