consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    DOTDIGITAL_API_URL: $DOTDIGITAL_API_URL
    DOTDIGITAL_API_USER: $DOTDIGITAL_API_USER
    DOTDIGITAL_API_PASSWORD: $DOTDIGITAL_API_PASSWORD
    DOTDIGITAL_LIST_SUBSCRIBER: $DOTDIGITAL_LIST_SUBSCRIBER
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
    COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
    COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
    COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
    COMMERCE_ADMIN_TOKEN: $COMMERCE_ADMIN_TOKEN
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
