consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    $include: ../../auth.config.yaml
    DOTDIGITAL_CATALOG_COLLECTION_NAME: $DOTDIGITAL_CATALOG_COLLECTION_NAME
  annotations:
    require-adobe-auth: true
    final: true
